### ISSUE TITLE
Unable to deploy flex application with enable_app_engine_apis: true as WAR

### ISSUE THREAD

**Issue by justindriggers** [GoogleCloudPlatform/app-gradle-plugin#188]
Migrating from the Managed VM `java-compat` runtime, following the instructions here: https://cloud.google.com/appengine/docs/flexible/java/upgrading#continuing_to_use_compat_runtimes

`src/appengine/app.yaml`:
```
service: my-application
runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 3.35
beta_settings:
  enable_app_engine_apis: true
health_check:
  enable_health_check: true
  check_interval_sec: 50
  timeout_sec: 30
  unhealthy_threshold: 10
  healthy_threshold: 5
  restart_threshold: 60
```

After running `appengineDeploy`, the following error is reported:
```
Starting Step #0
Step #0: INFO  - Identified Java artifact for deployment Artifact{type=WAR, path=/workspace/my-application.war}
Step #0: Exception in thread "main" com.google.cloud.runtimes.builder.buildsteps.base.BuildStepException: App Engine APIs have been enabled. In order to use App Engine APIs, an exploded WAR artifact is required, but a WAR artifact was found. See https://cloud.google.com/appengine/docs/flexible/java/upgrading for more detail.
Step #0: 	at com.google.cloud.runtimes.builder.buildsteps.RuntimeImageBuildStep.getBaseRuntimeImage(RuntimeImageBuildStep.java:76)
Step #0: 	at com.google.cloud.runtimes.builder.buildsteps.RuntimeImageBuildStep.run(RuntimeImageBuildStep.java:51)
Step #0: 	at com.google.cloud.runtimes.builder.BuildPipelineConfigurator.generateDockerResources(BuildPipelineConfigurator.java:96)
Step #0: 	at com.google.cloud.runtimes.builder.Application.main(Application.java:105)
Finished Step #0
```
Since the plugin detects that the application is a "flex" application, there is no `explodeWar` task, so I whipped one up:

```
appengine {
    stage {
        artifact = "$buildDir/exploded-app/"
    }
}

task explodeWar(type: Sync) {
    into appengine.stage.artifact
    with war
}

assemble.dependsOn explodeWar
```
However, that only results in an error complaining about the artifact not being a file:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task 'appengineStage'.
> File '${project_path}/my-application/build/exploded-app' specified for property 'stagingConfig.artifact' is not a file.
```
I believe that has to do with the `@InputFile` annotation on `StageFlexibleExtension#getArtifact()` (`@Input` supports files and directories).

To work around this, we are currently exploding the WAR _between_ the `appengineStage` and `appengineDeploy` tasks:

```
appengine {
    stage {
        stagingDirectory = "$buildDir/staged-app/"
    }
}

task cleanupWar(type: Delete) {
    delete fileTree(appengine.stage.stagingDirectory) {
        include '**/*.war'
    }
}

task explodeWar(type: Copy) {
    into appengine.stage.stagingDirectory
    with war
    finalizedBy cleanupWar
}

appengineStage {
    finalizedBy explodeWar
}
```
This way, the WAR is built and copied into the staged-app directory, and then exploded directly inside of the staged-app directory (while cleaning up the WAR so that it doesn't get built into the Dockerfile). Using this setup, the `appengineDeploy` task correctly deploys the exploded WAR with the enabled APIs using the flex runtime.

Ideally, I think the appengineStage task should simply detect the presence of `enable_app_engine_apis: true` in the `app.yaml`, and explode the WAR on its own.
